###
GET localhost:8080/api/store/111


###
POST localhost:8080/api/update/111
Content-Type: application/json

{
  "sku": "111",
  "command": "SET",
  "value": 15
}


###
POST localhost:8080/api/update/111
Content-Type: application/json

{
  "sku": "111",
  "command": "RESERVE",
  "value": 2
}

###
POST localhost:8080/api/update/111
Content-Type: application/json

{
  "sku": "111",
  "command": "RELEASE",
  "value": 3
}